from prometheus_client import Counter, Gauge, Histogram

ACK = Histogram("codestra_fast_ack_seconds", "Fast ACK total latency")
DB_COMMIT = Histogram("codestra_db_commit_seconds", "Ingress commit latency")
AUTH_FAILURES = Counter("codestra_auth_failures_total", "Authentication failures", ["kind"])
SCHEMA_REJECTIONS = Counter("codestra_schema_rejections_total", "Schema rejections")
IDEMPOTENT_REPLAYS = Counter("codestra_idempotent_replays_total", "Idempotent replays")
IDEMPOTENCY_CONFLICTS = Counter("codestra_idempotency_conflicts_total", "Idempotency conflicts")
QUEUE_DEPTH = Gauge("codestra_delivery_queue_depth", "Delivery queue depth", ["target", "status"])
OLDEST_AGE = Gauge("codestra_delivery_oldest_seconds", "Oldest delivery age", ["target"])
DLQ_DEPTH = Gauge("codestra_dlq_depth", "Dead-letter queue depth", ["target"])
RECONCILIATION_GAPS = Gauge("codestra_reconciliation_gaps", "Report-only reconciliation gaps", ["category"])

ORDER_RECEIVED = Counter("codestra_orders_received_total", "Orders received")
ORDER_VALIDATED = Counter("codestra_orders_validated_total", "Orders validated")
ORDER_APPROVED = Counter("codestra_orders_approved_total", "Orders approved")
ORDER_DISPATCHED = Counter("codestra_orders_dispatched_total", "Orders dispatched")
ORDER_STARTED = Counter("codestra_orders_started_total", "Orders started")
ORDER_COMPLETED = Counter("codestra_orders_completed_total", "Orders completed")
ORDER_FAILED = Counter("codestra_orders_failed_total", "Orders failed")
ORDER_RETRIED = Counter("codestra_orders_retried_total", "Orders retried")
ORDER_DEAD_LETTERED = Counter("codestra_orders_dead_lettered_total", "Orders dead-lettered")
ORDER_HUMAN_REVIEW = Counter("codestra_orders_human_review_total", "Orders sent to human review")
ORDER_DUPLICATE_SUPPRESSION = Counter("codestra_order_duplicate_suppression_total", "Duplicate orders suppressed")
ORDER_CALLBACK_FAILURE = Counter("codestra_order_callback_failure_total", "Order callback failures")
ORDER_PROGRESS = Counter("codestra_order_progress_total", "Order progress callbacks")
ORDER_SECURITY_RETRY = Counter("codestra_security_failure_retry_total", "Security failures never retried")
ORDER_RECONCILIATION_MISMATCH = Counter("codestra_order_reconciliation_mismatch_total", "Order reconciliation mismatches")
ORDER_QUEUE_DEPTH = Gauge("codestra_order_queue_depth", "Approved-order queue depth")
ORDER_STALE_RUNNING = Gauge("codestra_order_stale_running_total", "Stale running orders")
ORDER_WORKFLOW_DURATION = Histogram("codestra_order_workflow_duration_seconds", "Order workflow duration")
ORDER_QUEUE_DELAY = Histogram("codestra_order_queue_delay_seconds", "Order queue delay")
