"""Beyvra transactional email durable control plane.

Revision ID: 20260819_01
Revises: 0048_agent_call_realtime
"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone

revision = "20260819_01"
down_revision = "0048_agent_call_realtime"
branch_labels = None
depends_on = None

status = sa.Enum("CREATED", "QUEUED", "PROCESSING", "SUBMITTED", "SENT", "DELIVERED", "DEFERRED", "BOUNCED_SOFT", "BOUNCED_HARD", "COMPLAINED", "SUPPRESSED", "FAILED", "DEAD_LETTER", name="emailstatus")


def upgrade():
    op.create_table("email_tenant", sa.Column("tenant_id", sa.String(36), primary_key=True), sa.Column("account_id", sa.String(36), nullable=False, unique=True), sa.Column("slug", sa.String(80), nullable=False, unique=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("environment", sa.String(30), nullable=False), sa.Column("service_scope", sa.String(30), nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("email_service_identity_mapping", sa.Column("service_name", sa.String(120), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("email_tenant.tenant_id"), nullable=False), sa.Column("environment", sa.String(30), nullable=False), sa.Column("allowed_scopes", sa.JSON, nullable=False), sa.Column("active", sa.Boolean, nullable=False))
    op.create_table("email_department", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("email_tenant.tenant_id"), nullable=False), sa.Column("address", sa.String(320), nullable=False), sa.Column("slug", sa.String(80), nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.UniqueConstraint("tenant_id", "address", name="uq_email_department_address"), sa.UniqueConstraint("tenant_id", "slug", name="uq_email_department_slug"))
    tenant = sa.table("email_tenant", sa.column("tenant_id", sa.String), sa.column("account_id", sa.String), sa.column("slug", sa.String), sa.column("name", sa.String), sa.column("environment", sa.String), sa.column("service_scope", sa.String), sa.column("active", sa.Boolean), sa.column("created_at", sa.DateTime(timezone=True)))
    op.bulk_insert(tenant, [{"tenant_id": "49f847e4-9d0c-53af-9871-1abc7ff1b8cf", "account_id": "edc90db9-6f89-56dc-986c-d96c244c5f55", "slug": "beyvra", "name": "Beyvra", "environment": "production", "service_scope": "email", "active": True, "created_at": datetime.now(timezone.utc)}])
    identity = sa.table("email_service_identity_mapping", sa.column("service_name", sa.String), sa.column("tenant_id", sa.String), sa.column("environment", sa.String), sa.column("allowed_scopes", sa.JSON), sa.column("active", sa.Boolean))
    op.bulk_insert(identity, [{"service_name": "klyrow-email-provider", "tenant_id": "49f847e4-9d0c-53af-9871-1abc7ff1b8cf", "environment": "production", "allowed_scopes": ["email.inbound", "email.delivery_event"], "active": True}, {"service_name": "beyvra", "tenant_id": "49f847e4-9d0c-53af-9871-1abc7ff1b8cf", "environment": "production", "allowed_scopes": ["email.send", "email.read"], "active": True}])
    department = sa.table("email_department", sa.column("id", sa.String), sa.column("tenant_id", sa.String), sa.column("address", sa.String), sa.column("slug", sa.String), sa.column("active", sa.Boolean))
    names = ("support", "complaints", "onboarding", "kyc", "compliance", "aml", "fraud", "risk", "trading", "tradeops", "payments", "billing", "finance", "legal", "privacy", "dpo", "security", "abuse", "partners", "institutional", "press", "careers")
    op.bulk_insert(department, [{"id": f"beyvra-department-{index:02d}", "tenant_id": "49f847e4-9d0c-53af-9871-1abc7ff1b8cf", "address": f"{name}@beyvra.com", "slug": name, "active": True} for index, name in enumerate(names, 1)])
    op.create_table("email_template_version", sa.Column("template_id", sa.String(100), primary_key=True), sa.Column("version", sa.Integer, primary_key=True), sa.Column("locale", sa.String(20), primary_key=True), sa.Column("category", sa.String(30), nullable=False), sa.Column("subject", sa.String(255), nullable=False), sa.Column("text_body", sa.Text, nullable=False), sa.Column("html_body", sa.Text, nullable=False), sa.Column("required_variables", sa.JSON, nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("email_notification", sa.Column("notification_id", sa.String(36), primary_key=True), sa.Column("event_id", sa.String(200), nullable=False), sa.Column("correlation_id", sa.String(200), nullable=False), sa.Column("idempotency_key", sa.String(200), nullable=False), sa.Column("user_id", sa.String(200), nullable=False), sa.Column("account_id", sa.String(200), nullable=False), sa.Column("tenant_id", sa.String(200), nullable=False), sa.Column("template_id", sa.String(100), nullable=False), sa.Column("template_version", sa.Integer, nullable=False), sa.Column("recipient", sa.String(320), nullable=False), sa.Column("recipient_hash", sa.String(64), nullable=False), sa.Column("sender", sa.String(320), nullable=False), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("category", sa.String(30), nullable=False), sa.Column("locale", sa.String(20), nullable=False), sa.Column("parameters", sa.JSON, nullable=False), sa.Column("status", status, nullable=False), sa.Column("attempt_count", sa.Integer, nullable=False), sa.Column("last_error_class", sa.String(80)), sa.Column("provider_message_id", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("queued_at", sa.DateTime(timezone=True)), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("delivered_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_email_notification_tenant_idempotency"))
    for name, columns in (("ix_email_notification_event", ["tenant_id", "event_id"]), ("ix_email_notification_provider", ["provider_message_id"]), ("ix_email_notification_recipient", ["tenant_id", "recipient_hash"]), ("ix_email_notification_created", ["created_at"]), ("ix_email_notification_status", ["status"])):
        op.create_index(name, "email_notification", columns)
    op.create_table("email_outbox", sa.Column("notification_id", sa.String(36), sa.ForeignKey("email_notification.notification_id"), primary_key=True), sa.Column("status", sa.String(30), nullable=False), sa.Column("available_at", sa.DateTime(timezone=True), nullable=False), sa.Column("lease_owner", sa.String(100)), sa.Column("lease_expires_at", sa.DateTime(timezone=True)), sa.Column("attempt_count", sa.Integer, nullable=False), sa.Column("last_error_class", sa.String(80)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_email_outbox_claim", "email_outbox", ["status", "available_at", "lease_expires_at"])
    op.create_table("email_delivery_event", sa.Column("id", sa.String(36), primary_key=True), sa.Column("provider_event_id", sa.String(255), nullable=False, unique=True), sa.Column("provider_message_id", sa.String(255), nullable=False), sa.Column("notification_id", sa.String(36), sa.ForeignKey("email_notification.notification_id"), nullable=False), sa.Column("correlation_id", sa.String(200), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("normalized_status", status, nullable=False), sa.Column("payload_digest", sa.String(64), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_email_delivery_provider_message", "email_delivery_event", ["provider_message_id"])
    op.create_table("email_dead_letter", sa.Column("notification_id", sa.String(36), sa.ForeignKey("email_notification.notification_id"), primary_key=True), sa.Column("error_class", sa.String(80), nullable=False), sa.Column("error_digest", sa.String(64), nullable=False), sa.Column("attempt_count", sa.Integer, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("replayed_at", sa.DateTime(timezone=True)))
    op.create_table("email_suppression", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(200), nullable=False), sa.Column("recipient_hash", sa.String(64), nullable=False), sa.Column("reason", sa.String(40), nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "recipient_hash", "reason", name="uq_email_suppression_boundary"))
    op.create_table("email_department_member", sa.Column("id", sa.String(36), primary_key=True), sa.Column("department_id", sa.String(36), sa.ForeignKey("email_department.id"), nullable=False), sa.Column("employee_subject", sa.String(200), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("department_id", "employee_subject", name="uq_email_department_member"))
    op.create_table("email_case", sa.Column("id", sa.String(36), primary_key=True), sa.Column("tenant_id", sa.String(36), sa.ForeignKey("email_tenant.tenant_id"), nullable=False), sa.Column("department_id", sa.String(36), sa.ForeignKey("email_department.id"), nullable=False), sa.Column("thread_key", sa.String(255), nullable=False), sa.Column("subject", sa.String(998), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("tenant_id", "thread_key", name="uq_email_case_thread"))
    op.create_table("email_case_message", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("email_case.id"), nullable=False), sa.Column("provider_event_id", sa.String(255), nullable=False, unique=True), sa.Column("provider_message_id", sa.String(255)), sa.Column("message_id", sa.String(998), nullable=False), sa.Column("in_reply_to", sa.String(998)), sa.Column("references", sa.JSON, nullable=False), sa.Column("sender", sa.String(320), nullable=False), sa.Column("recipients", sa.JSON, nullable=False), sa.Column("cc", sa.JSON, nullable=False), sa.Column("subject", sa.String(998), nullable=False), sa.Column("message_date", sa.DateTime(timezone=True)), sa.Column("text_body", sa.Text), sa.Column("html_body", sa.Text), sa.Column("payload_digest", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("email_case_event", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("email_case.id"), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("actor_subject", sa.String(200)), sa.Column("event_metadata", sa.JSON, nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("email_attachment", sa.Column("id", sa.String(36), primary_key=True), sa.Column("message_id", sa.String(36), sa.ForeignKey("email_case_message.id"), nullable=False), sa.Column("filename", sa.String(255), nullable=False), sa.Column("content_type", sa.String(255), nullable=False), sa.Column("size_bytes", sa.Integer, nullable=False), sa.Column("content_digest", sa.String(64), nullable=False), sa.Column("storage_key", sa.String(500)), sa.Column("scan_status", sa.String(30), nullable=False))
    op.create_table("email_archive", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("email_case.id"), nullable=False, unique=True), sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False), sa.Column("retention_until", sa.DateTime(timezone=True)))
    op.create_table("email_legal_hold", sa.Column("id", sa.String(36), primary_key=True), sa.Column("case_id", sa.String(36), sa.ForeignKey("email_case.id"), nullable=False), sa.Column("reason", sa.Text, nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("released_at", sa.DateTime(timezone=True)))


def downgrade():
    for table in ("email_legal_hold", "email_archive", "email_attachment", "email_case_event", "email_case_message", "email_case", "email_department_member", "email_suppression", "email_dead_letter", "email_delivery_event", "email_outbox", "email_notification", "email_template_version", "email_department", "email_service_identity_mapping", "email_tenant"):
        op.drop_table(table)
    status.drop(op.get_bind(), checkfirst=True)
